[package]
edition = "2021"
name = "pyret_lexer"
version = "0.1.0"

[features]
color = ["ansi_term"]

[dependencies]
const_format = "0.2.19"
fancy-regex = "0.7.1"
once_cell = "1.8.0"

ansi_term = { version = "0.12.1", optional = true }
