[package]
authors = ["Lemuel DLS"]
categories = ["compilers", "parser-implementations", "wasm"]
default-run = "pyret"
description = "An implementation of the Pyret programming language."
edition = "2021"
keywords = ["pyret"]
license = "Apache-2.0"
name = "pyret"
version = "0.0.0"

[dependencies]
pyret-error = { path = "../error" }
pyret-interpreter = { path = "../interpreter" }

ansi_term = "0.12.1"
dirs-next = "2.0.0"
