[package]
authors = ["Lemuel DLS"]
categories = ["compilers", "parser-implementations", "wasm"]
default-run = "pyret"
edition = "2021"
keywords = ["pyret"]
name = "pyret"
version = "0.1.0"

[[bin]]
name = "pyret"

[features]
default = ["run", "pyret-transpiler/color"]

run = ["v8", "serde_v8"]

[dependencies]
clap = { version = "3.0.0", features = ["derive", "cargo", "wrap_help"] }

ansi_term = "0.12.1"
dirs = "4.0.0"
notify = "4.0.17"
rand = "0.8.4"
rustyline = "9.1.1"

serde_v8 = { version = "0.30.0", optional = true }
v8 = { version = "0.40.0", optional = true }

pyret-transpiler = { path = "../transpiler", features = ["color"] }
