[package]
edition = "2021"
name = "pyret-transpiler"
version = "0.1.0"

[features]
color = ["pyret-lexer/color", "pyret-runtime/color"]

[dependencies]
pyret-lexer = { path = "../lexer" }
pyret-runtime = { path = "../runtime" }
