[package]
edition = "2021"
name = "pyret-error"
version = "0.1.0-alpha.0"

[features]
default = []

fancy = ["pyret-file/fancy"]

[dependencies]
pyret-file = { path = "../file", version = "0.1.0-alpha.0" }

line-col = "0.2.1"
thiserror = "1.0.39"
