[package]
edition = "2021"
name = "pyret-interpreter-macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = { version = "1.0.107", features = ["full"] }
