[package]
edition = "2021"
name = "pyret_transpiler"
version = "0.1.0"

[features]
color = ["pyret_lexer/color", "pyret_runtime/color"]

[dependencies]
pyret_lexer = { path = "../lexer" }
pyret_runtime = { path = "../runtime" }
